// action常量
export const GET_NOTICELIST_LOADING = 'GET_NOTICELIST_LOADING'
export const GET_NOTICELIST_LOADING_SUCCESS = 'GET_NOTICELIST_LOADING_SUCCESS'
export const GET_NOTICELIST_LOADING_FAILD = 'GET_NOTICELIST_LOADING_FAILD'
export const GET_DETAIL_LOADING_SUCCESS='GET_DETAIL_LOADING_SUCCESS'